#!/usr/bin/env node
/**
 * Writes `docs/intrinsics.md` from the registry, so the specification of the operation set cannot
 * drift from the operations the compiler actually has.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { allIntrinsics } from "../src/intrinsics/index.ts";
import { effectsToString } from "../src/effects.ts";

const groups = new Map<string, { name: string; doc: string; effects: string; comptime: boolean }[]>();

for (const intrinsic of allIntrinsics()) {
	const module = intrinsic.name.split(".")[0]!;
	const rows = groups.get(module) ?? [];
	rows.push({
		name: intrinsic.name,
		doc: intrinsic.doc,
		effects: effectsToString(intrinsic.effects),
		comptime: intrinsic.comptime,
	});
	groups.set(module, rows);
}

const lines = [
	"# Intrinsics",
	"",
	"Generated by `npm run docs`. One row per operation the Core can express; everything else is",
	"source library code, which is the default answer (see the admission rule in",
	"[semantics.md](semantics.md)).",
	"",
	`There are ${allIntrinsics().length} intrinsics in ${groups.size} modules.`,
	"",
];

for (const [module, rows] of [...groups.entries()].sort(([left], [right]) => left.localeCompare(right))) {
	lines.push(`## \`${module}\``, "", "| operation | effects | comptime | meaning |", "| --- | --- | --- | --- |");
	for (const row of rows.sort((left, right) => left.name.localeCompare(right.name))) {
		lines.push(`| \`${row.name}\` | ${row.effects} | ${row.comptime ? "yes" : "no"} | ${row.doc} |`);
	}
	lines.push("");
}

writeFileSync(join(import.meta.dirname, "..", "docs", "intrinsics.md"), `${lines.join("\n")}\n`);
process.stdout.write(`docs/intrinsics.md: ${allIntrinsics().length} intrinsics\n`);
